title: ovis1mem1e's blog
description: 양한나의 블로그입니다.

url: https://github.com/ovis1me1me
paginate_path: "blog/page:num/" 
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: ovis1me1me's blog
      url: ovis1me1me.github.io
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: https://github.com/ovis1me1me
    twitter: 
    facebook: 
    email: ovis1me1me@gmail.com
    linkedin: 

google_analytics: ""

disqus:
    shortname: brianmaierjr
